# Generated by Django 4.2.16 on 2026-07-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
