# Generated by Django 4.2.16 on 2026-07-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_is_seen_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_approved_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
