# Generated by Django 4.2.16 on 2026-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_contract_approved_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen_by_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
